version = 3

[clientSideConfig]
	[clientSideConfig.modifyMaxVDConfig]
		enableExtRenderDistanceProtocol = false
		enabled = false

[noTickViewDistance]
	enableExtRenderDistanceProtocol = false


