hash-format = "sha256"

[[files]]
file = "config/debugify.json"
hash = "37371e9765144ef805550761ce0ef40ddf5ea78b568cbf53c1f270bae7e50024"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "fd3111c67003dc0719de6315b6e050f832b9c308e013764603e01b68c8a7e31d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "914525168bfe586ba692b0ea415d12671f4f9424eff5f40bb42a423fccb9539d"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "efe2da0a146fc7dd7487d01e36cd82837d7ef328a513592f309c6c023abc7c19"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "4b73d298117b248896e4b7baea676555293739fe19557d8641fd83cd6f12acdc"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "b04558e3aa16f01cb56278cbb0ae1a2a7c65b5288ee056865a07b2764a850f65"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "8b8445e529c08e91124b702dd286d279adf9535aadb38211c53f0706c29acb12"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "8950878c0bccb66ef8fd9acefce4adf42a2dae0b5ae286fd9ce6447f201cb251"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "03fd4b94f8e976d3c5b54e16fe61fc00d054ada322d09e32e9c457ca57d9e800"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "421afecc36a2bef3ae73685d00bb84207e5f9b608b0adb3485ded08b1ef772c9"

[[files]]
file = "config/yosbr/options.txt"
hash = "9e45c9b5a5a62e1cee87674834bec9ed306fe9202c169922393447f67913a0bc"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b4281fb5300c4de0d7dc9266cf7bdfa6255643522273757065dffe18fc1cef0d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "86498eb7f9326155844799dc57c1372fc5000b86f046994162cccd2e480a96ed"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "d02024521821336e40652c36c675ee520b4137ed73953e98f21bcf8a55f6a583"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "5d0871bb4dbf85c494447188feb58adb122c61f5f551a0239e6268d7c0327876"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "beaf8fcc2dbc9098a414bedd5a8ca156084b39f20517fac2ff60ad57f5767202"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "4e2a60e26cb6760c58dd2ed193f071c430b76cb542ebda0394cfacd220c12362"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "3c81b5e0df8efde86777b7a1b1a336376ae95dc97e5b0df6235d693428faf1a2"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "5907619c0a26d32e4b7b2f6de98eddeb192b523adfb6765dd73c3224e7be175b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4c1b893d87c51588985c483fe33193ca03cf3673de998eef6eeb850d8928e7ab"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "05bf4efb7aab56777e2f9d51b8113155749758de820d25d211813444f5469b5e"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "064fafff245baf812342dc9af4acf661dec663bab2a4067c65a27fa00860efb1"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "6682a581b77e820ea340d3279b7a49f5d311d3fa0b08b53628c9bf56a7c668ac"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "5b43c0fc6904ad4480c8ed596411c6e24172f8320ccd63de97b4ce2e7e0f90a5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c6932018158da544553f88b977bed1946f59d9c86685f2023b0a9ee196fc3087"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "bbf63ac8b9775c315526e0161daa609493a9a6168741077aca636e0123a2a4f4"
metafile = true

[[files]]
file = "mods/morecullingextra.pw.toml"
hash = "ad85600fddb58af75bee8cbf6807ac9b0bf0d57a2a963da8a57f77e80fe275b7"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "946275e17b2c860d1efb56d268a63c53fa9100953ea7759c4f7c22c3385734c9"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b2e3be698473bfb3f08865a11e74c9ee8d47239ac72a79d60acc1ee381722a50"
metafile = true

[[files]]
file = "mods/skip-transitions.pw.toml"
hash = "70b66e2a03d8a6531f0c6e71fa9d6d878ea8f42929ac43f4295b2a3111279b86"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "c8fd86f94fb1bc7def8fc00b4d0722992356c85ad574ce60f1c2c123750c2785"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1ab96020d0954a72b5cc150b375f57cf8968ac2c1809a000472076f8675eb9ea"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "f60dab2c1cf96a1d156c35f24fe90b1b6208202eb59caff77f6348066277e549"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "003dee7fef878abc298c3c6589b7b21e8922def090c9cf8259ae8c6aacc0946f"
metafile = true
