hash-format = "sha256"

[[files]]
file = "config/debugify.json"
hash = "37371e9765144ef805550761ce0ef40ddf5ea78b568cbf53c1f270bae7e50024"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "fd3111c67003dc0719de6315b6e050f832b9c308e013764603e01b68c8a7e31d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "914525168bfe586ba692b0ea415d12671f4f9424eff5f40bb42a423fccb9539d"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "efe2da0a146fc7dd7487d01e36cd82837d7ef328a513592f309c6c023abc7c19"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "4b73d298117b248896e4b7baea676555293739fe19557d8641fd83cd6f12acdc"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "b04558e3aa16f01cb56278cbb0ae1a2a7c65b5288ee056865a07b2764a850f65"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "8b8445e529c08e91124b702dd286d279adf9535aadb38211c53f0706c29acb12"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "8950878c0bccb66ef8fd9acefce4adf42a2dae0b5ae286fd9ce6447f201cb251"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "03fd4b94f8e976d3c5b54e16fe61fc00d054ada322d09e32e9c457ca57d9e800"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "421afecc36a2bef3ae73685d00bb84207e5f9b608b0adb3485ded08b1ef772c9"

[[files]]
file = "config/yosbr/options.txt"
hash = "9e45c9b5a5a62e1cee87674834bec9ed306fe9202c169922393447f67913a0bc"

[[files]]
file = "mods/better-beds.pw.toml"
hash = "112cb3b761a4ef017c2123fe61c0bcd0425d67ecbbc77ea76dd4f9c6842312bf"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "e4bbedd539a469daf66cf45717ccf5b8d2ba454d7e6b865c3a648fb8c4f80a40"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "77bd9b9ae2bf78481ba939cc78e5e4c0d9528516aa791305eecb39eb56e13125"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "4595621a88c273e5d0ab70dae5866d323122f449c668a667640ee79fbc6063f2"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ffc1f6d147394bfeb65b2fb9a78ca7d3365cbf5192c31af1312bc899190e4e34"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b668875d7f22033e43efeef4c1772f8567d6b33b06f7b16e17ccb3bbcb23dc47"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e4368d03d9745fa609d706cac8f595f061af10fdd0833c17e4e027c2d607e1fa"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "ef9ab1a9351ad20f6c5c061caa409d4024bcf8ad498dc4994d897ca1988c61ff"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "b2f3946270893de11c4d1b22fa401b648ac2807638e3bfe68827a6933725d3eb"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "112b6225f1559851e105b5b9b407d2a626579f443419b26386f26d0d06cc7267"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "f19e328fe42f91d1b65e244ee5bcf70f1e5305a27278945098ea85af82e05d0d"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "219d4425679c60fd2855a6a39a6fccb6db3948dcc57b9da7c20907c855c5bd3d"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "ea127e8f74006f3a9ce099f9e96adaa3b3f4f281231ece703c4e7f9732137ebd"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9480f9e11e91eb82ba616c5c622c218d7b7ceff6599a3348d557eb1a1ddd41f9"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "f61810be98ef52436d3355ecfa4354bc47d142cbe9468fbd14415e5bc6d66125"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "ec64297b6b7f82ede5ecc46a82e8a0e8dc8b730ee2ad763427b7043389b7a072"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b99c1cae57386de36e5a6dc1d247057d0d5c0e9c5a5563b67d078ea7975919a9"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "4ef251bf925c957e46fa3b223933425df85611d4ddf0e7a04949b38783800a65"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "57a8bedb0057a988cc3a02ed62ef5dcc3331d65df1e7cbebac3789e92858bea0"
metafile = true

[[files]]
file = "mods/skip-transitions.pw.toml"
hash = "70b66e2a03d8a6531f0c6e71fa9d6d878ea8f42929ac43f4295b2a3111279b86"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "2af323bd9b84abdcf8ace4e8bf9eacafacb9c8f3c980643354697de24cfa3080"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d1480fd38a1ac53311baa2d57b92556834372f6ac04c355169441df9a59a161c"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "99f9628800ccabd189b9bb28859f01caaf9ad672f247ae875e3eaa5f965f9406"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "d94f9ad5bbcda1ed1ac5ee7855db8ea638461c507122ed37689ee9a715aaf838"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "003dee7fef878abc298c3c6589b7b21e8922def090c9cf8259ae8c6aacc0946f"
metafile = true
