hash-format = "sha256"

[[files]]
file = "config/debugify.json"
hash = "37371e9765144ef805550761ce0ef40ddf5ea78b568cbf53c1f270bae7e50024"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "fd3111c67003dc0719de6315b6e050f832b9c308e013764603e01b68c8a7e31d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "914525168bfe586ba692b0ea415d12671f4f9424eff5f40bb42a423fccb9539d"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "efe2da0a146fc7dd7487d01e36cd82837d7ef328a513592f309c6c023abc7c19"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "4b73d298117b248896e4b7baea676555293739fe19557d8641fd83cd6f12acdc"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "b04558e3aa16f01cb56278cbb0ae1a2a7c65b5288ee056865a07b2764a850f65"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "8b8445e529c08e91124b702dd286d279adf9535aadb38211c53f0706c29acb12"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "8950878c0bccb66ef8fd9acefce4adf42a2dae0b5ae286fd9ce6447f201cb251"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "03fd4b94f8e976d3c5b54e16fe61fc00d054ada322d09e32e9c457ca57d9e800"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "421afecc36a2bef3ae73685d00bb84207e5f9b608b0adb3485ded08b1ef772c9"

[[files]]
file = "config/yosbr/options.txt"
hash = "5808cb6d24a5533dc2fcfe50cdd1b6bcb5681f5a9bcb018a64dae42ba3f59453"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "f551f7780b8d32345f7c4646137d1ed91fb7f24e3a61d998d6fc5b366f44b4a0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "213cad77d46ff46fe20780b01856cb1a8812747e9c3564203669bf3905e646e2"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "783c0415795fc4bea6d85315aac54d3a3f2770fcd02d66dad1f626b311f8bf4f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "81a389a5035dc0852ce12c796f1d667bb4715b1d6ffde16433bf80f02e3796bc"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "bf886d03a194a4036f02afe690cb21ca346fff20f4193355994ec97f046a8809"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "ed622deb60304758f1f8ee69e33f057b2d95ab1b65cddc4218978e9255814b77"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "46a497398e476b0bbac4a1c9816da987be2a9afc2e62011d584963beef0ba45e"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "f25e49ca19098f7488d30092719c0a8e480da5f01b6e7069bf1093fea82c80a8"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7d36d5a19b32363dc9795b0f4610705e332c0100169b2ec4a54654b0923ba89f"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "77e9a02e09ec5a0d6682e5f448953048d99e36da299d92627044aff0828798e3"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4716789e4a806c1cabcef27e67150215edb4c3d737e9a87d90f2f615d6c196cd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "be0fd8b9cd9f8a94428ea8ac5ec84f4f7bab23697236b7a2e54d8537834e0315"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "79e31e1697a4121696b9a1817ff75ebe58af1514f132cdc64522d4ca4e0cdd08"
metafile = true

[[files]]
file = "mods/morecullingextra.pw.toml"
hash = "ad85600fddb58af75bee8cbf6807ac9b0bf0d57a2a963da8a57f77e80fe275b7"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "0f9e287c84c2463ecb376d58c8bf30cbfbfa04ec44aef2f61e36e42fe529be30"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b2e3be698473bfb3f08865a11e74c9ee8d47239ac72a79d60acc1ee381722a50"
metafile = true

[[files]]
file = "mods/skip-transitions.pw.toml"
hash = "70b66e2a03d8a6531f0c6e71fa9d6d878ea8f42929ac43f4295b2a3111279b86"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8da0d4c285e7e57aee3f08ab4e268d04518704ace4060744f042aef3a7f6bc50"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "003dee7fef878abc298c3c6589b7b21e8922def090c9cf8259ae8c6aacc0946f"
metafile = true
