name: Automatically publish to Modrinth
on:
  release:
    types: [published]
jobs:
  publish-to-modrinth:
    runs-on: ubuntu-22.04
    steps:
       - name: Download the pack files
         uses: robinraju/release-downloader@v1.5
         with:
           github-token: ${{ secrets.GITHUB }}
           name: "*.mrpack"
           latest: true
           tarBall: false
           zipBall: false
           out-file-path: .
           
 #1.18.2           
       - name: Publish 1.18.2
         uses: Kir-Antipov/mc-publish@v3.2
         with:
           modrinth-id: ehPxCT2J
           modrinth-token: ${{ secrets.MODRINTH }}
           modrinth-unfeature-mode: subset
           modrinth-files: '*1.18.2.mrpack'
           name: 'Quilt Optimized for 1.18.2'
           version-type: 'beta'
           loaders: quilt
           game-versions: '1.18.2'
#1.19.2       
       - name: Publish 1.19.2
         uses: Kir-Antipov/mc-publish@v3.2
         with:
           modrinth-id: ehPxCT2J
           modrinth-token: ${{ secrets.MODRINTH }}
           modrinth-unfeature-mode: subset
           modrinth-files: '*1.19.2.mrpack'
           name: 'Quilt Optimized for 1.19.2'
           version-type: 'beta'
           loaders: quilt
           game-versions: '1.19.2'
             
#1.19.3             
       - name: Publish 1.19.3
         uses: Kir-Antipov/mc-publish@v3.2
         with:
           modrinth-id: ehPxCT2J
           modrinth-token: ${{ secrets.MODRINTH }}
           modrinth-unfeature-mode: subset
           modrinth-files: '*1.19.3.mrpack'
           name: 'Quilt Optimized for 1.19.3'
           version-type: 'beta'
           loaders: quilt
           game-versions: '1.19.3'
           
#1.19.4 wip
       - name: Publish 1.19.4
         uses: Kir-Antipov/mc-publish@v3.2
         with:
           modrinth-id: ehPxCT2J
           modrinth-token: ${{ secrets.MODRINTH }}
           modrinth-unfeature-mode: subset
           modrinth-files: '*1.19.4.mrpack'
           name: 'Quilt Optimized for 1.19.4 Test'
           version-type: 'alpha'
           loaders: quilt
           game-versions: '23w06a'
           

        
